#!/usr/bin/env bash
# Bash script that configures an Ubuntu server and changes
# the home IP address by restarting the network interface.

sed -i '/localhost/ s/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
