#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with:
# localhost to 127.0.0.2
# facebook.com to 8.8.8.8

sed -i '/localhost/ s/127.0.0.1/127.0.0.2/' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
