#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with:
# localhost to 127.0.0.2
# facebook.com to 8.8.8.8

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
